[package]
name = "file_crawler"
version = "0.1.0"
authors = ["Bob Hoeppner <bobahop@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
walkdir = "2"
